/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.senac.telas;

import br.com.senac.bancodedados.AcoesDAO;
import br.com.senac.bolsadevalores.Acoes;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodolfo
 */
public class CadastroAcao extends javax.swing.JFrame {

    /**
     * Creates new form CadastroAcao
     */
    public CadastroAcao() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoTicker = new javax.swing.JTextField();
        campoNome = new javax.swing.JTextField();
        campoCnpj = new javax.swing.JTextField();
        botaoBuscar = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();
        botaoEditar = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();
        botaoCadastar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Ação");

        jPanel1.setBackground(new java.awt.Color(30, 58, 138));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CADASTRAR AÇÃO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(226, 226, 226))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("CNPJ (somente números):");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Tiker:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Nome:");

        campoTicker.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoTicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTickerActionPerformed(evt);
            }
        });
        campoTicker.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoTickerKeyTyped(evt);
            }
        });

        campoNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeActionPerformed(evt);
            }
        });

        campoCnpj.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCnpjActionPerformed(evt);
            }
        });
        campoCnpj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoCnpjKeyTyped(evt);
            }
        });

        botaoBuscar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botaoBuscar.setForeground(new java.awt.Color(37, 99, 235));
        botaoBuscar.setText("Buscar pelo Tiker");
        botaoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarActionPerformed(evt);
            }
        });

        botaoVoltar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botaoVoltar.setForeground(new java.awt.Color(37, 99, 235));
        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        botaoEditar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botaoEditar.setForeground(new java.awt.Color(37, 99, 235));
        botaoEditar.setText("Editar");
        botaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarActionPerformed(evt);
            }
        });

        botaoExcluir.setBackground(new java.awt.Color(255, 0, 0));
        botaoExcluir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botaoExcluir.setForeground(new java.awt.Color(255, 255, 255));
        botaoExcluir.setText("Excluir");
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });

        botaoCadastar.setBackground(new java.awt.Color(0, 153, 51));
        botaoCadastar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botaoCadastar.setForeground(new java.awt.Color(255, 255, 255));
        botaoCadastar.setText("Cadastrar");
        botaoCadastar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(botaoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(botaoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(botaoCadastar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoCnpj, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .addComponent(campoTicker)
                    .addComponent(campoNome))
                .addGap(32, 32, 32)
                .addComponent(botaoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoTicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(29, 29, 29)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoCadastar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoTickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTickerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTickerActionPerformed

    private void campoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeActionPerformed

    private void campoCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCnpjActionPerformed

    private void campoTickerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoTickerKeyTyped
        // TODO add your handling code here:
        if (campoTicker.getText().length() >= 5) {
            evt.consume();
        }
    }//GEN-LAST:event_campoTickerKeyTyped

    private void botaoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarActionPerformed
        String ticker = campoTicker.getText();
        
        if (ticker.isEmpty()) {
            return;            
        }
        
               
        AcoesDAO acoesDao = new AcoesDAO();
        
        if(acoesDao.isEmpty()){
            JOptionPane.showMessageDialog(this, "Erro de Conexão com o Banco de Dados!");
            return;
        }
        
        Acoes acao = acoesDao.pesquisar(ticker);
        
        if(acao == null){
            JOptionPane.showMessageDialog(this, "Ação não encontrada!");
            campoNome.setText("");
            campoCnpj.setText("");
            campoTicker.setText("");
        }
        else{
            campoNome.setText(acao.getNome());
            campoCnpj.setText(acao.getCnpj());
            campoTicker.setText(acao.getTicker());
        }
        
        
    }//GEN-LAST:event_botaoBuscarActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void botaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarActionPerformed
        if(campoTicker.getText().isEmpty()){
            return;
        }
            
        if (campoNome.getText().isEmpty() || campoCnpj.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos!");
            return;
        }
            
        String ticker = campoTicker.getText();
        String nome = campoNome.getText();
        String cnpj = campoCnpj.getText();
            
            
            
        Acoes acao = new Acoes();
        acao.setNome(nome);
        acao.setCnpj(cnpj);
        acao.setTicker(ticker);
            
        AcoesDAO acoesDao = new AcoesDAO();
            
        if(acoesDao.isEmpty()){
            JOptionPane.showMessageDialog(this, "Erro de Conexão com o Banco de Dados!");
            return;
        }
            
        if(acoesDao.editar(acao)){
            JOptionPane.showMessageDialog(this, "Dados Atualizados com sucesso.");   
                
            campoNome.setText("");
            campoCnpj.setText("");
            campoTicker.setText("");
        }
        else{
            JOptionPane.showMessageDialog(this, "Erro em atualizar os dados.");
        }
    }//GEN-LAST:event_botaoEditarActionPerformed

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        String ticker = campoTicker.getText();
        
        if (ticker.isEmpty()) {
            return;            
        }
                     
        AcoesDAO acoesDao = new AcoesDAO();
        
        if(acoesDao.isEmpty()){
            JOptionPane.showMessageDialog(this, "Erro de Conexão com o Banco de Dados!");
            return;
        }
        
        if(acoesDao.excluir(ticker)){
            JOptionPane.showMessageDialog(this, "Dados excluídos com sucesso!");
            campoNome.setText("");
            campoCnpj.setText("");
            campoTicker.setText("");
        }
        else{
            JOptionPane.showMessageDialog(this, "Erro ao executar a exclusão, ação possui Compras/Vendas Cadastradas ou não existe!");
        }
    }//GEN-LAST:event_botaoExcluirActionPerformed

    private void botaoCadastarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastarActionPerformed

        if (campoNome.getText().isEmpty() || campoCnpj.getText().isEmpty() || campoTicker.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos!");
            return;
        }
            
        String ticker = campoTicker.getText();
        String nome = campoNome.getText();
        String cnpj  = campoCnpj.getText();
            
        Acoes acao = new Acoes();
        acao.setNome(nome);
        acao.setCnpj(cnpj);
        acao.setTicker(ticker);
            
        AcoesDAO acoesDao = new AcoesDAO();
            
        if(acoesDao.isEmpty()){
            JOptionPane.showMessageDialog(this, "Erro de Conexão com o Banco de Dados!");
            return;
        }
            
        if(acoesDao.cadastrar(acao)){
            JOptionPane.showMessageDialog(this, "Dados inseridos com sucesso.");   
                
            campoNome.setText("");
            campoCnpj.setText("");
            campoTicker.setText("");
        }
        else{
            JOptionPane.showMessageDialog(this, "Erro para inserir os dados.");
        }       
    }//GEN-LAST:event_botaoCadastarActionPerformed

    private void campoCnpjKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoCnpjKeyTyped
        if (campoCnpj.getText().length() >= 14) {
            evt.consume();
        }
    }//GEN-LAST:event_campoCnpjKeyTyped

 
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoBuscar;
    private javax.swing.JButton botaoCadastar;
    private javax.swing.JButton botaoEditar;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JTextField campoCnpj;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoTicker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
