/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.senac.telas;

import br.com.senac.bancodedados.AcoesDAO;
import br.com.senac.bancodedados.ComprasDAO;
import br.com.senac.bancodedados.VendasDAO;
import br.com.senac.bolsadevalores.Acoes;
import br.com.senac.bolsadevalores.Compras;
import br.com.senac.bolsadevalores.Vendas;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodolfo
 */
public class RegistrarVenda extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarVenda
     */
    public RegistrarVenda() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        listarAcoes();
    }
    
    private void listarAcoes(){
        try {
            
            comboAcoes.removeAllItems();
            AcoesDAO acoesDao = new AcoesDAO();
            
            if(acoesDao.isEmpty()){
                JOptionPane.showMessageDialog(this, "Erro de Conexão com o Banco de Dados!");
                return;
            }
            
            
            
            List<Acoes> listagem = acoesDao.getAcoes();
            
            for(int i = 0; i < listagem.size(); i++){
                comboAcoes.addItem(listagem.get(i).getTicker() + " - " + listagem.get(i).getNome());
            }
            
        } catch (Exception e) {
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        botaoRegistrar = new javax.swing.JButton();
        campoData = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comboAcoes = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        botaoVoltar = new javax.swing.JButton();
        campoQnt = new javax.swing.JTextField();
        campoValor = new javax.swing.JTextField();
        campoCusto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Venda de Ação");

        jPanel3.setBackground(new java.awt.Color(30, 58, 138));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("REGISTRA VENDA");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(270, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        botaoRegistrar.setBackground(new java.awt.Color(0, 153, 51));
        botaoRegistrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botaoRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        botaoRegistrar.setText("Registrar Venda");
        botaoRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRegistrarActionPerformed(evt);
            }
        });

        try {
            campoData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoData.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Ação:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Quantidade:");

        comboAcoes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        comboAcoes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Valor Unitário:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Data:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Custo Unitário (taxas):");

        botaoVoltar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botaoVoltar.setForeground(new java.awt.Color(37, 99, 235));
        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        campoQnt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoQnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoQntActionPerformed(evt);
            }
        });
        campoQnt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoQntKeyTyped(evt);
            }
        });

        campoValor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoValorActionPerformed(evt);
            }
        });
        campoValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoValorKeyTyped(evt);
            }
        });

        campoCusto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoCusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCustoActionPerformed(evt);
            }
        });
        campoCusto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoCustoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(campoValor, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoQnt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboAcoes, javax.swing.GroupLayout.Alignment.LEADING, 0, 299, Short.MAX_VALUE)
                            .addComponent(campoCusto)
                            .addComponent(campoData)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(botaoRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(comboAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(campoQnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(campoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(jLabel8))
                    .addComponent(campoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(campoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRegistrarActionPerformed
        try{
            Integer quantidade;
            Double valor;
            Double custo;
            
            if (campoCusto.getText().isEmpty() || campoData.getText().isEmpty() || campoQnt.getText().isEmpty() || campoValor.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Preencha todos os campos!");
                return;
            }
            
            try {
                quantidade = Integer.valueOf(campoQnt.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Quantidade inválida!");
                return;
            }
            
            try {
                String txtValor = campoValor.getText();
                String txtCusto = campoCusto.getText();
                txtValor = txtValor.replace(",", ".");
                txtCusto =  txtCusto.replace(",", ".");
                
                valor = Double.valueOf(txtValor);
                custo = Double.valueOf(txtCusto);
                
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Valor inválido em Valor e/ou Custo!");
                return;
            }
            
            SimpleDateFormat sdfData = new SimpleDateFormat("dd/MM/yyyy");
            sdfData.setLenient(false);
            Date data = sdfData.parse(campoData.getText());
            
            Vendas venda = new Vendas();
            
            venda.setQuantidade(quantidade);
            venda.setValor(valor);
            venda.setCusto(custo);
            venda.setData(data);
            
            String selecionado = comboAcoes.getSelectedItem().toString();
            String ticker = selecionado.split(" - ")[0];
            venda.setTickerAcao(ticker);
            
            VendasDAO vendasDao = new VendasDAO();
            
            if(vendasDao.isEmpty()){
                JOptionPane.showMessageDialog(this, "Erro de Conexão com o Banco de Dados!");
                return;
            }
            
            if(vendasDao.cadastrar(venda)){
                JOptionPane.showMessageDialog(this, "Dados inseridos com sucesso.");
                campoValor.setText("");
                campoQnt.setText("");
                campoData.setText("");
                campoCusto.setText("");
            }
            else{
                JOptionPane.showMessageDialog(this, "Erro para inserir os dados.");
            }
            
        }
        catch(java.text.ParseException e){
            JOptionPane.showMessageDialog(this, "Data inválida!");
        }
        
        
        
    }//GEN-LAST:event_botaoRegistrarActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void campoQntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoQntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoQntActionPerformed

    private void campoQntKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoQntKeyTyped
        // TODO add your handling code here:
        if (campoQnt.getText().length() >= 5) {
            evt.consume();
        }
    }//GEN-LAST:event_campoQntKeyTyped

    private void campoValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoValorActionPerformed

    private void campoValorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoValorKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_campoValorKeyTyped

    private void campoCustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCustoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCustoActionPerformed

    private void campoCustoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoCustoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCustoKeyTyped

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoRegistrar;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JTextField campoCusto;
    private javax.swing.JFormattedTextField campoData;
    private javax.swing.JTextField campoQnt;
    private javax.swing.JTextField campoValor;
    private javax.swing.JComboBox<String> comboAcoes;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
